/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedDocumentoIdRouteImport } from './routes/_authenticated/documento.$id'
import { Route as ApiPublicCriarPoPendenteRouteImport } from './routes/api/public/criar-po-pendente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentoIdRoute =
  AuthenticatedDocumentoIdRouteImport.update({
    id: '/documento/$id',
    path: '/documento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCriarPoPendenteRoute =
  ApiPublicCriarPoPendenteRouteImport.update({
    id: '/api/public/criar-po-pendente',
    path: '/api/public/criar-po-pendente',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/documento/$id': typeof AuthenticatedDocumentoIdRoute
  '/api/public/criar-po-pendente': typeof ApiPublicCriarPoPendenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/documento/$id': typeof AuthenticatedDocumentoIdRoute
  '/api/public/criar-po-pendente': typeof ApiPublicCriarPoPendenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/documento/$id': typeof AuthenticatedDocumentoIdRoute
  '/api/public/criar-po-pendente': typeof ApiPublicCriarPoPendenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/historico'
    | '/indicadores'
    | '/painel'
    | '/documento/$id'
    | '/api/public/criar-po-pendente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/historico'
    | '/indicadores'
    | '/painel'
    | '/documento/$id'
    | '/api/public/criar-po-pendente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/historico'
    | '/_authenticated/indicadores'
    | '/_authenticated/painel'
    | '/_authenticated/documento/$id'
    | '/api/public/criar-po-pendente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCriarPoPendenteRoute: typeof ApiPublicCriarPoPendenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documento/$id': {
      id: '/_authenticated/documento/$id'
      path: '/documento/$id'
      fullPath: '/documento/$id'
      preLoaderRoute: typeof AuthenticatedDocumentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/criar-po-pendente': {
      id: '/api/public/criar-po-pendente'
      path: '/api/public/criar-po-pendente'
      fullPath: '/api/public/criar-po-pendente'
      preLoaderRoute: typeof ApiPublicCriarPoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedDocumentoIdRoute: typeof AuthenticatedDocumentoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedDocumentoIdRoute: AuthenticatedDocumentoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCriarPoPendenteRoute: ApiPublicCriarPoPendenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
